services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - "--appendonly yes"  # Enable data persistence
      - "--appendfilename redis-data.aof"  # Set the AOF filename
      - "--dir /data"  # Set the working directory for AOF files
      - "--requirepass ${REDIS_PASSWORD}"  # Set Redis password
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
