services:
  redis-master:
    image: redis
    container_name: redis-master
    restart: always
    volumes:
      - redis_master:/data
    ports:
      - 6379:6379

  redis-replica1:
    image: redis
    container_name: redis-replica1
    restart: always
    volumes:
      - redis_replica1:/data
    ports:
      - 6479:6379
    command: redis-server --replicaof redis-master 6379
volumes:
  redis_master:
  redis_replica1:
networks:
  redis-net:
    driver: bridge
  