services:
  redis-master:
    image: redis
    container_name: redis-master
    restart: always
    volumes:
      - redis_master:/data
    ports:
      - 6379:6379

  redis-slave1:
    image: redis
    container_name: redis-slave1
    restart: always
    volumes:
      - redis_slave1:/data
    ports:
      - 6479:6379
    command: redis-server --slaveof redis-master 6379
volumes:
  redis_master:
  redis_slave1:
  